/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExecucaoDeTestes.java
 *
 * Created on 31/01/2011, 17:12:55
 */
package ui;

import fachada.*;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import ui.util.ExibirTempo;
import ui.util.PesquisaConsultas;
import ui.util.ThreadConfiguracaoTestes;

/**
 *
 * @author Pedro Holanda
 */
public class ConfiguracaoDeTestes extends JInternalFrame {

    /** Creates new form ExecucaoDeTestes */
    public ConfiguracaoDeTestes() {
        initComponents();
    }
    boolean rodada;
    boolean tempo;
    static int id;
    static boolean configuracaoAcabou = false;
    AcompanhamentoTestes janela = new AcompanhamentoTestes();
    TelaPrincipal telaPrincipal;

    /* public JInternalFrame getJanela(){
    return janela;
    }*/
    public boolean configuracaoAcabou() {
        return configuracaoAcabou;
    }
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DadosAcesso3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jQuantidadeIteracoes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jOrdem = new javax.swing.JComboBox();
        jExecutar = new javax.swing.JButton();
        jTipo = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setTitle("dBest - Configuração de Testes");

        DadosAcesso3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Teste", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setText("Tipo de Teste :");

        jLabel11.setText("Quantidade de Iterações:");

        jQuantidadeIteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuantidadeIteracoesActionPerformed(evt);
            }
        });

        jLabel10.setText("Ordem do teste : ");

        jOrdem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sequencial", "Aleatório", "Aleatório pré-definida", " " }));

        jExecutar.setText("Executar");
        jExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExecutarActionPerformed(evt);
            }
        });

        jTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Por Iterações", "Por Tempo" }));
        jTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DadosAcesso3Layout = new javax.swing.GroupLayout(DadosAcesso3);
        DadosAcesso3.setLayout(DadosAcesso3Layout);
        DadosAcesso3Layout.setHorizontalGroup(
            DadosAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosAcesso3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(DadosAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jQuantidadeIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DadosAcesso3Layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(jExecutar)
                .addContainerGap())
        );

        DadosAcesso3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jOrdem, jQuantidadeIteracoes, jTipo});

        DadosAcesso3Layout.setVerticalGroup(
            DadosAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DadosAcesso3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DadosAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DadosAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(DadosAcesso3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jQuantidadeIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jExecutar)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DadosAcesso3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DadosAcesso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jQuantidadeIteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuantidadeIteracoesActionPerformed
    }//GEN-LAST:event_jQuantidadeIteracoesActionPerformed

    private void jExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExecutarActionPerformed
        FachadaDeConfiguracao fachadaDeConfiguracao = new FachadaDeConfiguracao();
        ConexaoBanco dados = new ConexaoBanco();
        ThreadConfiguracaoTestes threadConfiguracao = new ThreadConfiguracaoTestes();
        PesquisaConsultas consultasP = new PesquisaConsultas();
        ExibirTempo tempoE = new ExibirTempo();
        String tipo;
        String ordem = "Aleatorio pre-definido";
        threadConfiguracao.setDados(dados);
        threadConfiguracao.setOrdem(jOrdem.getSelectedIndex() + 1);
        threadConfiguracao.setTipo(jTipo.getSelectedIndex());
        if (jTipo.getSelectedIndex() == 0) {
            int iteracoes = Integer.parseInt(jQuantidadeIteracoes.getText());
            threadConfiguracao.setIteracao(iteracoes);
            tipo = "Iteracao";
        } else {
            int tempo = Integer.parseInt(jQuantidadeIteracoes.getText());
            threadConfiguracao.setTempo(tempo);
            tipo = "Tempo";
        }
        if (jOrdem.getSelectedIndex() == 0) {
            ordem = "Sequencial";
        } else if (jOrdem.getSelectedIndex() == 1) {
            ordem = "Aleatorio";
        }

        this.setVisible(false);
        //janela.run();
        janela.setDadosTeste(dados.getBenchmark().getNome(), tipo, ordem,jQuantidadeIteracoes.getText());
        janela.setVisible(true);
        threadConfiguracao.setJanela(janela);
        this.getDesktopPane().add(janela);
        threadConfiguracao.start();
        consultasP.setTeste(janela);
        tempoE.setTela(janela);
        consultasP.start();
        tempoE.start();
        configuracaoAcabou = true;
    }//GEN-LAST:event_jExecutarActionPerformed

    private void jTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTipoActionPerformed
        if (jTipo.getSelectedIndex() == 1) {
            jLabel11.setText("Tempo (min):");           
        }
         if (jTipo.getSelectedIndex() == 0) {
            jLabel11.setText("Quantidade de Iterações:"); 

        }
    }//GEN-LAST:event_jTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ConfiguracaoDeTestes().setVisible(true);
            }
        });
    }

    public int getID() {
        return id;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DadosAcesso3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jExecutar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jOrdem;
    private javax.swing.JTextField jQuantidadeIteracoes;
    private javax.swing.JComboBox jTipo;
    // End of variables declaration//GEN-END:variables
}
